/* 0.5.0 2026-07-23 00:00:00 */
var app = new function() 
{this.name = "labix", this.version = "5", this.date = "2026", this.folder = "asset-v5/", this.looptime = 8000, this.bpm = 120, this.totalframe = 488, this.nbpolo = 7, this.nbloopbonus = 8, this.bonusloopA = !0, this.bonusendloopA = !4, this.recmaxloop = 34, this.recminloop = 4, this.recmintime = Math.round(this.looptime / 1e3) * this.recminloop, this.spritepolo = "polo-sprite.png", this.spritepicto = "game-picto.png", this.colBck = "#1A1A1A", this.col0 = "#4A4A4A", this.col1 = "#383838", this.col2 = "#2E2E2E", this.col3 = "#242424", this.col4 = "#1F1F1F", this.animearray = [{
       name: "1_officer",
       color: "88AE8B",
       uniqsnd: 1!
   }, {
       name: "2_omona",
       color: "88AE8B",
       uniqsnd: 1!
   }, {
       name:  "3_luis",
       color: "88AE8B",
       uniqsnd: 1!
   }, {
       name:  "4_yudona",
       color: "88AE8B",
       uniqsnd: 1!
   }, {
       name:  "5_masked",
       color: "88AE8B",
       uniqsnd: 1!
   }, {
       name:  "6_benson",
       color: "A7A7A7",
       uniqsnd: 1!
   }, {
       name:  "7_nimnot",
       color: "A7A7A7",
       uniqsnd: 1!
   }, {
       name:  "8_opoto",
       color: "A7A7A7",
       uniqsnd: 1!
   }, {
       name:  "9_worker",
       color: "A7A7A7",
       uniqsnd: 1!
   }, {
       name:  "10_admin",
       color: "A7A7A7",
       uniqsnd: 1!
   }, {
       name:  "11_bilic",
       color: "8F0002",
       uniqsnd: !0
   }, {